version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - cd my-webapp
      - mvn clean install
  post_build:
    commands:
      - echo "Current working directory:"
      - pwd 
      - echo "Build Completed Successfully"
      - ls -l target/
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker images
      - echo "Docker Push to ECR"
      - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Docker Pushed Successfuly"
artifacts:
  files:
    - "my-webapp/target/*.jar"
  discard-paths: yes
