# Use official OpenJDK image as the base
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/my-app-1.0-SNAPSHOT.jar /app/my-app.jar

# Expose the port on which the app will run
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/my-app.jar"]
